### ISSUE TITLE
Add the ability to change the base container image as a configuration option.

### ISSUE THREAD

**Issue by cowmix** [fat-tire/resolve#12]
Active development of Centos 7 (the preferred distribution by BMD for Resolve) ended in 2020.   This repo currently uses Centos 8 Stream as the base container image. It would be cool to be able to lean on other RedHat derivatives like Centos 9 Stream, RockyOS and AlmaLinux. 

I have manually tested most of these alternative base images however it would be good to have this as a runtime configuration parameter.

**Comment by fat-tire** [comment]
So essentially, all your base images belong to us?
