### ISSUE TITLE
making nvidia drivers work

### ISSUE THREAD

**Issue by no1-editor** [fat-tire/resolve#18]
i am noob so please excuse 

When installing some old nvidia drivers there needs to be --accept-license or is fails

like this

&& bash /tmp/NVIDIA-Linux-${ARCH}-${NVIDIA_VERSION}.run --no-kernel-module --no-kernel-module-source --run-nvidia-xconfig --no-backup --no-questions --accept-license --ui=none \

**Comment by fat-tire** [comment]
Oh, really?  This isn't needed for newer versions. I tried adding `--accept-license` and didn't run into any problems.  It built as normal.

Sounds like `--accept license` should be added to the `Dockerfile` and then I think the `RESOLVE_ACCEPT_LICENSE` (and the initial "Do you accept the license" question) should ask to confirm for this one too.

Thanks!  I'll add this ASAP.

**Comment by fat-tire** [comment]
As you can see, this should be fixed now!  Thanks so much!
