### ISSUE TITLE
How to use resolve.rc file with desktop shortcut?

### ISSUE THREAD

**Issue by WGandy** [fat-tire/resolve#28]
I've been trying a myriad of different syntaxes to add the environment variable 
`RESOLVE_RC_PATH=./resolve.rc`
to the bash line in the desktop file and so far nothing is working. 
(I need internet access to the container for use with a network library. )

**Comment by fat-tire** [comment]
So in `~/.local/share/applications/resolve.desktop` try changing this line:

     Exec=bash -c "cd $HOME/containers/resolve && ./resolve.sh"

to

     Exec=bash -c "cd $HOME/container/resolve && env RESOLVE_RC_PATH=$HOME/container/resolve/resolve.rc ./resolve.sh

See if that works for ya!  (depending on your directory names, you may need to make adjustments)

**Comment by WGandy** [comment]
Aha! That syntax does work. I had not tried using 'env' within the quotes of the bash line but it makes sense. 
It would be great if this little tidbit was on the main instructions page.

**Comment by fat-tire** [comment]
Or maybe just put it there by default?  Anyone have any opinions?

**Comment by fat-tire** [comment]
Added a pr for this, so gonna close
