### ISSUE TITLE
Missing H.264/H.265 render options with nvidia card

### ISSUE THREAD

**Issue by WGandy** [fat-tire/resolve#29]
Everything appears to be installed correctly. I installed the latest nvidia linux drivers on the Linux Mint 21 host before doing the installation instructions for fat-tire resolve. In Preferences in Resolve I see my Quadro T1000 card showing up with CUDA selected. But when I go to the render page I don't see h.264/5 options under Quicktime. 
I had this same video card working with these options (on a previous OS build) when I installed Resolve 18 directly on Debian 11 with the makeresolvedeb script. 

Any ideas why this isn't working?

**Comment by fat-tire** [comment]
Hmm.  Do you see the H264/265 options under mp4?

**Comment by fat-tire** [comment]
Just checked and I *do* see the H264/H265 options under Quicktime in the render page... fwiw.

Driver Version: 520.56.06

**Comment by WGandy** [comment]
> Hmm. Do you see the H264/265 options under mp4?

I don't recall seeing MP4 as an option. But Quicktime was. 

But, I decided to install DR18 Studio directly on the host with makeresolvedeb and now, the h.264/5 options are showing up on both the native AND the Podman install. So, it seems that the Tuffvesson script installed something on the host that was missing before. I didn't install any more nvidia driver packages or make any changes to it on the host. 
Nvidia 520 drivers are what I had installed to begin with.  Also, I'm seeing the MP4 category now as well. h.264/5 are available under MP4 and Quicktime.

**Comment by fat-tire** [comment]
Ah hah!  Cool, glad you figured it out...  as mentioned x264 (the open source version of [H.264/MPEG-4 AVC](https://en.wikipedia.org/wiki/H.264/MPEG-4_AVC)) is also available.

Gonna close this for now.  If any other issues arise, feel free to reopen!  Thx again.
