### ISSUE TITLE
qt error messages

### ISSUE THREAD

**Issue by bcnx** [fat-tire/resolve#3]
Hi,

on Linux Mint 20.3 launching Resolve results to this in the ResolveDebug.txt:

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Seems a QT related error in Mint. Anyone any clue on how to fix it? ldd shows no missing libraries.

Cheers,

BC

**Comment by fat-tire** [comment]
Could something be missing on the host side?  This [thread](https://forum.qt.io/topic/93247/qt-qpa-plugin-could-not-load-the-qt-platform-plugin-xcb-in-even-though-it-was-found) suggests setting `QT_DEBUG_PLUGINS=1` and looking for an error.

Does this stop Resolve from running entirely or only specific operations cause issues?

**Comment by fat-tire** [comment]
You didn't say whether you were using podman or docker, but based on [this](https://forum.qt.io/topic/125009/problem-with-qt-qpa-plugin-running-on-a-docker-in-kubuntu/17) I'm wondering if you need to add `xcb-util` to the list of installed packages to [line 34 in the Dockerfile.](https://github.com/fat-tire/resolve/blob/main/Dockerfile#L34)

If it works, let me know!  Thx.

**Comment by fat-tire** [comment]
Since it only added 22k to the build, I figured this was good to have regardless.  [So I added it](https://github.com/fat-tire/resolve/commit/d8da86c932c2d598883813598f96a0c4f7d0c921).

I'll give this issue a few more days if you want to confirm it fixed the issue.  Otherwise, closing.  Reopen if it is still a problem.

**Comment by fat-tire** [comment]
Six days later... closing as no response.  Hopefully working now tho.
