### ISSUE TITLE
log4cxx error under podman

### ISSUE THREAD

**Issue by rsevero** [fat-tire/resolve#31]
When trying resolve image under podman I get the following error:

```
log4cxx: No appender could be found for logger (BtCommon).
log4cxx: Please initialize the log4cxx system properly.
Failed to create Application support Dirs
```

Under docker it works fine.

Trying it on Fedora 37.

Any ideas on how to solve this issue?

**Comment by fat-tire** [comment]
Could this be a permission problem with the container accessing the `mounts/logs` directory?  Can you check to make sure it is owned by the user/group you are running podman from?  Also, you could try manually starting the container with a shell (ie, `./resolve.sh /bin/bash`) and then try creating a file with `touch /opt/resolve/logs/test.txt` from within the container?  See if it works, and if so, who the file is owned by.

(If the directory was created by docker running as root, perhaps it has root ownership so is inaccessible to podman?)

**Comment by fat-tire** [comment]
Did this help fix your issue?  I'll close this issue if I don't hear back in a few days...  thanks!

**Comment by fat-tire** [comment]
It's been a few days.  Hope you got everything working.  Feel free to re-open if you need more help!

**Comment by garyritchie** [comment]
Getting this too, with podman on Ubuntu 22.04. Does look like perms issue:

```bash
bash-5.1$ touch /opt/resolve/logs/test.txt
touch: setting times of '/opt/resolve/logs/test.txt': Permission denied
```

Permissions seem fine:

```bash
...
drwxrwxr-x 1 resolve gary  152 Feb  4 15:06  logs
...
```

...so, I suspect it could be that the file system where my resolve folder is on the host could be the issue: ntfs.

**Comment by GameVogue** [comment]
I am on Fedora 39 and I also have this issue. Running `touch /opt/resolve/logs/test.txt` to test results in `touch: cannot touch '/opt/resolve/logs/test.txt': Permission denied`

**Comment by fat-tire** [comment]
are you running with docker or podman?  Could you try verifying the info [requested](https://github.com/fat-tire/resolve/issues/31#issuecomment-1399339546) above?

**Comment by fat-tire** [comment]
> Did this help fix your issue? I'll close this issue if I don't hear back in a few days... thanks!

Closing as no response for > a month.  Hopefully now all is working.
