### ISSUE TITLE
Does not launch from ntfs-3g mounted partition

### ISSUE THREAD

**Issue by garyritchie** [fat-tire/resolve#32]
podman/docker on Ubuntu 22.04. Does look like perms issue:

```bash
bash-5.1$ touch /opt/resolve/logs/test.txt
touch: setting times of '/opt/resolve/logs/test.txt': Permission denied
```

Permissions seem fine:

```bash
...
drwxrwxr-x 1 resolve gary  152 Feb  4 15:06  logs
...
```

...so, I suspect it could be that the filesystem where my resolve folder is on the host could be the issue: **ntfs-3g**.

EDIT:

I moved everything to `~/resolve/`, which is an **ext4 filesystem**, (after deleting what was in `resolve/mounts/`) and also tried Docker -- with success:

```bash
$ RESOLVE_RC_PATH=./resolve.rc ./resolve.sh
Running:   ./resolve.rc
./env-set.sh: line 11: ./resolve.rc: No such file or directory
non-network local connections being added to access control list
------------------------------------------------------------------------------
No "container-machine-id" file found for this container.
Creating new one derived from host machine-id (cd12b4c5318d4f3c87a8bdffc2deceda)...
This container's machine-id file can now be found at /home/gary/resolve/mounts/container-machine-id and may be replaced if needed.
The container's /etc/machine-id  : 63f5f8237a527730a494e8549b5d244d
The network driver setting is          : --network=none
Bind-mounted directories of interest   :
  CONTAINER (CentOS 8)                  -> HOST (Ubuntu)
  ----------------------------------------------------------------------------
  /home/resolve                         -> /home/gary/resolve/mounts/resolve-home
  /opt/resolve/logs                     -> /home/gary/resolve/mounts/logs
  /opt/resolve/configs                  -> /home/gary/resolve/mounts/configs
  /opt/resolve/easyDCP                  -> /home/gary/resolve/mounts/easyDCP
  /opt/resolve/.license                 -> /home/gary/resolve/mounts/license
  /opt/resolve/'Resolve Disk Database'  -> /home/gary/resolve/mounts/database
  /var/BlackmagicDesign/DaVinci Resolve -> /home/gary/resolve/mounts/BlackmagicDesign
  /opt/resolve/Media                    -> /home/gary/resolve/mounts/Media
ActCCMessage Already in Table: Code= c005, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= c006, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= c007, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= 2282, Mode=  0, Level=  0, CmdKey= 8, Option= 0
PnlMsgActionStringAdapter Already in Table: Code= 615e, Mode=  0, Level=  0, CmdKey= -1, Option= 0
log4cxx: No appender could be found for logger (BtCommon).
log4cxx: Please initialize the log4cxx system properly.
QSocketNotifier: Can only be used with threads started with QThread
18.1.2.0006 Linux/Clang x86_64
Main thread starts: BD7A16C0
0x7ff5bd7a16c0 | Undefined            | INFO  | 2023-02-04 15:40:46,426 | --------------------------------------------------------------------------------
0x7ff5bd7a16c0 | Undefined            | INFO  | 2023-02-04 15:40:46,426 | Loaded log config from /home/resolve/.local/share/DaVinciResolve/configs/log-conf.xml
0x7ff5bd7a16c0 | Undefined            | INFO  | 2023-02-04 15:40:46,426 | --------------------------------------------------------------------------------
FusionScript Server [471] Started
Host 'Fusion' [1] Added
```

Podman also works. This project is impressive.

EDIT2:

I switched the filesystem used for that partition from **ntfs-3g** (or _auto_, in Ubuntu's Disk manager) to **ntfs3** and Resolve launches as expected.

```bash
$ uname -r
5.15.0-60-generic
```

Hoping that the new ntfs3 driver proves reliable as I still need to dual-boot Win10 occasionally.

**Comment by fat-tire** [comment]
Huh-- haven't tried it with ntfs, only ext4.   I wasn't even aware of any differnce  etween ntfs-3g vs ntfs3 and came up with [this](https://www.paragon-software.com/us/home/ntfs3-driver-faq/):

> What’s the difference between original kernel NTFS support, NTFS-3G and NTFS3 by Paragon?
> --
> Original Kernel level support for NTFS was contributed into a Linux Kernel back in 2001 and is very limited in functionality, especially write-support. Till now, NTFS-3G was the de facto way to enable NTFS in Linux. However, NTFS-3G is a filesystem in userspace (FUSE). The main drawback of this implementation is performance. On the contrary, NTFS3 is a kernel NTFS implementation, which offers much faster performance than FUSE based implementations. | Original Kernel level support for NTFS was contributed into a Linux Kernel back in 2001 and is very limited in functionality, especially write-support. Till now, NTFS-3G was the de facto way to enable NTFS in Linux. However, NTFS-3G is a filesystem in userspace (FUSE). The main drawback of this implementation is performance. On the contrary, NTFS3 is a kernel NTFS implementation, which offers much faster performance than FUSE based implementations.
> Original Kernel level support for NTFS was contributed into a Linux Kernel back in 2001 and is very limited in functionality, especially write-support. Till now, NTFS-3G was the de facto way to enable NTFS in Linux. However, NTFS-3G is a filesystem in userspace (FUSE). The main drawback of this implementation is performance. On the contrary, NTFS3 is a kernel NTFS implementation, which offers much faster performance than FUSE based implementations.

Looks from this that NTFS-3G wouldn't really be expected to perform well as opposed to NFTS3 because of the FUSE implementation.

Side-question re this:

> log4cxx: No appender could be found for logger (BtCommon).
> log4cxx: Please initialize the log4cxx system properly.

Do you happen to know if the logger is working as shown here:

>  /opt/resolve/logs                     -> /home/gary/resolve/mounts/logs

That is, are you able to see the `rollinglog.txt` files there?  I don't get that warning.

Thanks for the kind words re the project.  If you have any thoughts or contributions, please let us know!

**Comment by fat-tire** [comment]
Also looking for anyone to try RESOLVE_BUILD_X264_ENCODER_PLUGIN=1 ...  I've had great success with this software CPU-based encoder, but giving it a little more time before building it becomes the default.

**Comment by garyritchie** [comment]
>> /opt/resolve/logs -> /home/gary/resolve/mounts/logs
> 
> That is, are you able to see the `rollinglog.txt` files there? I don't get that warning.

I did the install on another [older laptop] and observed 64 lines in that text file. Didn't get past activation without the dongle. I'll check the workstation install when I get back to the office tomorrow.

> Also looking for anyone to try RESOLVE_BUILD_X264_ENCODER_PLUGIN=1 ... I've had great success with this software CPU-based encoder, but giving it a little more time before building it becomes the default.

No errors observed when rebuilding the container with that flag set. When restarting resolve (``) the `rollinglog.txt` file increased to 122 lines...

[rollinglog.txt](https://github.com/fat-tire/resolve/files/10611641/rollinglog.txt)

This is on an HP ZBook 15 G5 with Nvidia P2000 -- so maybe just an install tester for Resolve. (I did not bother to fetch the dongle for this.)

**Comment by garyritchie** [comment]
Well, this is a little embarrassing. I simplified the mount options for the ntfs partition, like so:

`/dev/disk/by-uuid/... /mnt/production auto defaults 0 0`

and Resolve starts. In addition the "log4cxx" messages are no longer present.

**Comment by fat-tire** [comment]
Oh great!  Thanks for reporting back..
