### ISSUE TITLE
[RESOLVED!] Can't get LUT loaded

### ISSUE THREAD

**Issue by c0debreaker** [fat-tire/resolve#47]
I tried  the LUTS that I was using in desktop versin of 18.6.4.  The version I am using now in docker is the same version. However, it cannot find LUT. I placed it in 

resolve/mounts/resolve-home/.local/share/DaVinciResolve/.LUT
also in /.local/share/DaVinciResolve/Fusion/LUTs

However, even after restart it, it doesn't show the LUTs I added.

**Comment by fat-tire** [comment]
Yeah, I think your first location, something like `/home/youraccount/docker/resolve/mounts/resolve-home/.local/share/DaVinciResolve/.LUT` should be the right one. (The exact path will depend on where you've installed the git repository and the mount folders)

To verify, when you go into the container, say with `./resolve.sh /bin/bash`, do you see the files at `/home/resolve/.local/share/DaVinciResolve/.LUT`?  You can also just do:  `./resolve.sh /bin/ls -la /home/resolve/.local/share/DaVinciResolve/.LUT`

I'm not sure how exactly you got the LUTs into the `.LUT` directory, but make sure not only that the LUT files are there as expected, but that the permissions and ownership makes the files accessible to the program.  They should probably match the other LUT files that are already there.  If needed, you can change the permissions or owner with `chmod` or `chown` from inside the container or outside from the host.

A final thought-- you can also add your own LUT Locations in the settings:  From a project, in the top menu bar, choose **DaVinci Resolve**->**Preferences**.  Make sure the **System** tab is active, then under **General**, you can select **LUT Locations**.  Then select **Add** or **Remove**.

Hope this helps. Let me know!

**Comment by c0debreaker** [comment]
Sorry, it's been so crazy at work! I'll try this later. Thank you so much!

**Comment by c0debreaker** [comment]
I remember now. On my non-docker-based Davinci Resolve, I can open the LUT folder when I click the button. However, with my docker-based Davinci Resolve, nothing happens when I click it. It doesn't show any errors. Maybe if I move a new LUT in that location and restart Davinci Resolve, it might parse. I will try it.
![image](https://github.com/fat-tire/resolve/assets/3783931/8882215c-88e5-4604-97d0-fc3b6e522e58)

**Comment by c0debreaker** [comment]
Oh, wow, your trick in your last paragraph worked! Thank you so much! The next thing I need to figure out are my hundreds of fonts :D

**Comment by fat-tire** [comment]
Glad you got the LUTs sorted.  Re the fonts-- did you happen to see [this section in the README](https://github.com/fat-tire/resolve?tab=readme-ov-file#whats-the-deal-with-fonts--where-are-they-coming-from)?

**Comment by c0debreaker** [comment]
Very cool! I'll try it later. Thanks a lot! :)

**Comment by c0debreaker** [comment]
I've followed the instructions. The environment variable worked. However, it looks like the fonts weren't getting rendered properly. I think 98% look the same. I guess I have like 150 fonts. What do you think is going on?

**Comment by fat-tire** [comment]
So you're saying the fonts are there and listed in the pull-down but are not rendered correctly?  Is it possible that they are in an unsupported format or something?

**Comment by c0debreaker** [comment]
Yes, the fonts are now showing in the pulldown in Davinci Resolve. Previously, I only saw like 15 fonts. Now, I see more than 100 fonts. However, there are fonts that I installed with fc-cache and I don't see them. I can see the fonts working in other applications though. I'll try to move them to /usr/share/fonts. I'll report back later.

**Comment by fat-tire** [comment]
Okay, yeah- I'm guessing that it's now pointing to the /usr/share/fonts (hence the zillion fonts-- probably the system fonts), so basically you want to get the fonts you want (that rhymes!) in the folder it's looking at...  keep me posted, and if you have any suggestions for improving the default behavior, let me know.  Thanks!

**Comment by c0debreaker** [comment]
I finally got it to work. First thing I tried was put it in /usr/local/share/fonts. That didn't work. The next destination was in /usr/share/fonts/opentype. The font I copied was `Blacksword.otf`. Here's the complete steps I did, if in case someone in the future encounters the same issues:
```
1. cd /usr/share/fonts
2. mkdir opentype/blacksword
3. sudo cp /home/myname/.fonts/Blacksword.otf opentype/blacksword
```
And for folks whole read this, the `.fonts` directory is where I've always placed fonts I've downloaded. For the downloaded fonts to work, I have to run `fc-cache -f -v`.  This is what I did when I was still using Davinci Resolve non-docker-based. With Fat-tire, you don't do this. Just follow the instructions above. Don't forget to put `export RESOLVE_ENABLE_HOST_SYSTEM_FONTS="YES"` in either ~/.bashrc orr ~/.zshrc.

I'm heading to work soon. I'll copy all the other fonts tonight.

Thank you so much! :)

**Comment by c0debreaker** [comment]
![image](https://github.com/fat-tire/resolve/assets/3783931/37930237-d564-4aca-b75c-1691d66d6dc7)

**Comment by c0debreaker** [comment]
Even more simpler. I created two directories under opentype and truetype. I called them AllOtherTTFs and AllOtherOTFs. I copied all my .otf files to AllOtherOTFs and .ttf to AllOtherTTFs. It worked!
https://github.com/fat-tire/resolve/assets/3783931/46d139d4-2875-4577-94e5-431604576367

**Comment by fat-tire** [comment]
Looks gorgeous! Congrats!

**Comment by c0debreaker** [comment]
Thanks for all the help! 😊
