### ISSUE TITLE
Resolve fails to start after a previous system crash

### ISSUE THREAD

**Issue by c0debreaker** [fat-tire/resolve#48]
When the system crash happened, I was using Davinci Resolve via fat-tire.

Now when I start it, I am now getting an error message. I don't know if it's fat-tire related or something broke in my system.
Here's the output when I start `./resolve.sh`

```
non-network local connections being added to access control list
e611ac7fb2c1
e611ac7fb2c1
------------------------------------------------------------------------------
The container's /etc/machine-id  : f2af41ea76a20fe44741d4bb9945c1a4
The network driver setting is          : --network=none
Bind-mounted directories of interest   :
  CONTAINER (CentOS 8)                  -> HOST (Debian GNU/Linux)
  ----------------------------------------------------------------------------
  /home/resolve                         -> /home/rcamara/containers/resolve/mounts/resolve-home
  /opt/resolve/logs                     -> /home/rcamara/containers/resolve/mounts/logs
  /opt/resolve/configs                  -> /home/rcamara/containers/resolve/mounts/configs
  /opt/resolve/easyDCP                  -> /home/rcamara/containers/resolve/mounts/easyDCP
  /opt/resolve/.license                 -> /home/rcamara/containers/resolve/mounts/license
  /opt/resolve/'Resolve Disk Database'  -> /home/rcamara/containers/resolve/mounts/database
  /var/BlackmagicDesign/DaVinci Resolve -> /home/rcamara/containers/resolve/mounts/BlackmagicDesign
  /opt/resolve/Media                    -> /home/rcamara/containers/resolve/mounts/Media
docker: Error response from daemon: error gathering device information while adding custom device "/dev/nvidia-uvm": no such file or directory.
```

**Comment by fat-tire** [comment]
Interesting as I havent' seen this error before.  I did a quick search and came up with [this thread.](https://old.reddit.com/r/qnap/comments/s7bbv6/fix_for_missing_nvidiauvm_device_devnvidiauvm/)  The issue they're discussing relates to running Plex (a media server) also in a container.

You didn't mention your version of Linux and nvidia hardware, but does it match your missing /dev/nvidia-uvm situation, and if so, might the script they suggested there help to recreate it?  It may also be worth taking a look [here](https://old.reddit.com/r/debian/comments/svp0go/nvidiauvm_doesnt_load_at_boot/) and I wonder if, no matter what the distro, it may be worthwhile looking into reinstalling the nvidia drivers-- perhaps the nvidia-uvm kernel module isn't loaded the next time you restarted?  (`lsmod` should show you the currently loaded kernel modules)

**Comment by c0debreaker** [comment]
Cool! I'll try the script mention in that link. Thank you so much!

Last night, I loaded the nvidia_uvm module and it shows up in lsmod. However, /dev/nvidia_uvm or /dev/nvidia-uvm didn't show  up. If it works, I don't know what the crashing did to my system.

I'll keep you posted. Oh, I'm on Debian 12 and GTX 1080 card.

**Comment by c0debreaker** [comment]
This is so weird. I haven't tried the script from that Reddit link yet. I was about to execute `rmmod nvidia_uvm` so I can execute the script, then I decided to look at the nvidia* in dev. I see nvidia-uvm device now. I am pretty sure that when I ran `sudo modprobe nvidia_uvm` last night, the device wasn't created. And resolve.sh proves it wasn't there.

Here's the result of `ls -l /dev | grep nvidia`
```
╰─ ls -lrt /dev |grep nvidia                                                                                                                                                                                          ─╯
crw-rw-rw-   1 root    root    195, 255 Mar 19 21:53 nvidiactl
crw-rw-rw-   1 root    root    195,   0 Mar 19 21:53 nvidia0
crw-rw-rw-   1 root    root    195, 254 Mar 19 21:53 nvidia-modeset
drwxr-xr-x   2 root    root       80 Mar 19 22:44 nvidia-caps
crw-rw-rw-   1 root    root    240,   1 Mar 19 23:16 nvidia-uvm-tools
crw-rw-rw-   1 root    root    240,   0 Mar 19 23:16 nvidia-uvm
```
If resolve.sh works, I don't know what fixed it.

I'll let you know soon.

**Comment by c0debreaker** [comment]
Yeah, it's so weird. It's good now!

![Screenshot from 2024-03-20 14-25-48](https://github.com/fat-tire/resolve/assets/3783931/5676aa74-1f54-4215-bc87-f6b3e0343d42)

**Comment by fat-tire** [comment]
Wow.  Not sure what happened exactly, but it seems more system related than related to the resolve stuff... so I'm gonna close this.  Thanks for reporting, and glad you got it working!
