### ISSUE TITLE
[Help] How can I install something in system without lost after close the bash

### ISSUE THREAD

**Issue by Milor123** [fat-tire/resolve#51]
Guys I am trying install a app, for example python, or ruby using yum install, and it works but when I close and open again it, I lose all :/ 

What need I modify ?
please help me, sorry i am very noob in podman

# Edit 1: 
I've tried follow the next tutorial from [https://phoenixnap.com/kb/how-to-commit-changes-to-docker-image](https://phoenixnap.com/kb/how-to-commit-changes-to-docker-image) :

Note: after try use this guide, When I open the `resolve.sh` it open in bash or sh, but dont open the program and dont load the ENV, becuase if I try open resolve typing /opt/resolve/bin/resolve, i need manually add in the console `__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia __VK_LAYER_NV_optimus=NVIDIA_only ` else davinci dont open.

PD 2:  I've removed the `--rm \`  from `resolve.sh` for follow the tutorial 

================================================

How to Commit Changes to a New Docker Image

The steps you must take to create a Docker image based on another image involves:

* Running a container from the base image.
* Making the necessary changes in the container.
* Committing the changes to a new image.

Follow the steps below to create a new Docker image using **`docker commit`**:

1\. Use **`docker run`** with the **`-it`** flag to launch a container in the interactive mode and enable a terminal typing interface. Specify the interface shell as the last command argument.

```plain
docker run -it [image] [shell]
```

```plain
docker run -it ubuntu /bin/bash
```

```plain
apt install nmap -y
```

```plain
exit
```

```plain
docker ps -a
```

```plain
docker commit [container-id] [new-image-name]
```

```plain
docker commit c624caff45a8 ubuntu-with-nmap
```

```plain
docker images
```

================================================

**Comment by fat-tire** [comment]
Was this resolved?

**Comment by Milor123** [comment]
> ¿Se resolvió esto?

Yes thank u very much !, I've added the changes in build script
