### ISSUE TITLE
Cant Load LUTs V2

### ISSUE THREAD

**Issue by Milor123** [fat-tire/resolve#57]
Hi guys, I've read all this thread https://github.com/fat-tire/resolve/issues/47

and I tell you? the most curious thing was that I was solving this problem as the author quoted in his final paragraph:

> A final thought-- you can also add your own LUT Locations in the settings: From a project, in the top menu bar, choose **DaVinci Resolve**->**Preferences**. Make sure the **System** tab is active, then under **General**, you can select **LUT Locations**. Then select **Add** or **Remove**.

It happened that the disk where I saved the presets got burned (it was an old NTFS HDD), so today I went to try to put my LUTS backups in its place to replace it.

Apparently davinci allows me to import the place in the external path that I had created, but the problem is that it never loads them, they don't appear anywhere, neither the folder names.

![Captura de pantalla_20240812_095253](https://github.com/user-attachments/assets/2aef0373-9dab-4f80-b25c-c437ca3103de)

All my files of docker (no images) are in `/home/noe/Documentos/resolve/`

I **was using a normal rute** in **RESOLVE_BIND_TARGETS**, **but now** trying solve this also I've used `/home/resolve/.local/share/DaVinciResolve/.LUT/`

```
RESOLVE_BIND_SOURCES=(... "/home/noe/Documentos/resolve/Davinci-Presets/MyLUTS/")
RESOLVE_BIND_TARGETS=("... " "/home/resolve/.local/share/DaVinciResolve/.LUT/")
```

But nothings works, also try from my real machine use chmod -R 777 over Luts folder, chown -R noe:noe, and the permissions inside of the podman dont allow chage it.

Could be it a permissions error?

Note, add information (try mount the LUTS in home/resolve/Davinci-Presets/):

```
From inside podman
./resolve.sh /usr/bin/bash
bash-4.4$ cd home/resolve/Davinci-Presets/
bash-4.4$ ls -l *

Mios:
total 1272
-rwxrwxrwx 1 resolve resolve 431272 Aug 12 08:50 LUT-Dehancer-Rec.709-Kodak_Vision3_250D-33.cube_shaperlut
-rwxrwxrwx 1 resolve resolve 431272 Aug 12 08:50 Ludwig-Dehancer-Rec.709-Kodak_Vision3_250D-33.cube_shaperlut
-rwxrwxrwx 1 resolve resolve 431272 Aug 12 08:50 ludwig-LUT-Dehancer-Rec.709-Kodak_Vision3_250D-33.cube_shaperlut

```

**Comment by Milor123** [comment]
I am not sure if it error is somthing of permission but while i keep in the resolver script rute, in my case: `/home/noe/Documentos/resolve/` I cant mount files from here

Now I've put my luts of my real machine  outside from `resolve` folder

Real machine other folder:
`/home/noe/Documentos/LUTs/`

And now can map it
RESOLVE_BIND_SOURCES=(... "/home/noe/Documentos/LUTs/")
RESOLVE_BIND_TARGETS=("... " "/home/resolve/Davinci-Presets/")

and add `/home/resolve/Davinci-Presets/` to :
> A final thought-- you can also add your own LUT Locations in the settings: From a project, in the top menu bar, choose **DaVinci Resolve**->**Preferences**. Make sure the **System** tab is active, then under **General**, you can select **LUT Locations**. Then select **Add** or **Remove**.

Now works without problem. 
Surely it is a permission problem, why? Because when i tried modify files from resolve forder of my realmachine (the folder that have resolve.sh), it always ask for root permissions.

### With it has been resolved for now.
Thank u very much !

**Comment by fat-tire** [comment]
I'm glad it's working...  podman is a little strange with the permissions since you're running rootless, but as long as you've got it working, that's great to hear!

**Comment by fat-tire** [comment]
I'm gonna close this.  If you want to re-open it or think it should be moved to a discussion, let me know!  Thanks.

**Comment by Milor123** [comment]
> I'm gonna close this. If you want to re-open it or think it should be moved to a discussion, let me know! Thanks.

Hahah its true, man you very much bro !!
