### ISSUE TITLE
Is the documentation correct? - no `nvidia-container-runtime` in Apt

### ISSUE THREAD

**Issue by jbreckmckye** [fat-tire/resolve#62]
In my case I installed the Nvidia Container Toolkit instead, instructions [here](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installation).

**Comment by fat-tire** [comment]
Yes, you're right. It looks like it was [deprecated](https://github.com/NVIDIA/nvidia-container-runtime/commit/6ce593a81232bedbee743d79808f54664246ff63).  The container toolkit is the preferred solution now, so the documentation should be updated.

**Comment by jbreckmckye** [comment]
@fat-tire PR opened (#63)

**Comment by fat-tire** [comment]
Thanks!  This is great & very clear.

You know what's really weird, my host doesn't have _either_ nvidia-container-runtime OR the toolkit and it still runs fine.  It only  has a recent nvidia driver installed, and I wonder if that's enough (?)

Q: Did you try running without it per chance? (also, which distro & nvidia driver version are you using?)

**Comment by fat-tire** [comment]
Also- are you using docker or podman?  I am using podman so I wonder if it's a docker requirement (since the illustration on the toolkit page shows docker in there)...  let me know-- this is certainly better than what is there now for sure.

**Comment by jbreckmckye** [comment]
Hmm. For the moment I've altered the patch to mark this is as `[OPTIONAL]`. But, to be honest, I am not 100% clear when you do and don't need the NVIDIA container toolkit (I actually don't really know how containers interact with GPUs....)

**Comment by fat-tire** [comment]
Yeah I'm not sure either but it replaces the old outdated instruction, so that's definitely an improvement over what was there previously.  I merged, so thank you so very much!

I'll close this, but feel free to re-open if there's anything to add :)
