### ISSUE TITLE
log4cxx error at launch

### ISSUE THREAD

**Issue by pperquin** [fat-tire/resolve#9]
hi,

I have this when try to launch:

./resolve.sh
/home/pil/containers/resolve
PODMAN
/home/pil/containers/resolve
non-network local connections being added to access control list
------------------------------------------------------------------------------
The container's /etc/machine-id  : f9e164346eb00127f7c72b8e4b951048
The network driver setting is          : --network=none
Bind-mounted directories of interest   :
  CONTAINER (CentOS 8)                  -> HOST (Ubuntu)
  ----------------------------------------------------------------------------
  /home/resolve                         -> /home/pil/containers/resolve/mounts/resolve-home
  /opt/resolve/logs                     -> /home/pil/containers/resolve/mounts/logs
  /opt/resolve/configs                  -> /home/pil/containers/resolve/mounts/configs
  /opt/resolve/easyDCP                  -> /home/pil/containers/resolve/mounts/easyDCP
  /opt/resolve/.license                 -> /home/pil/containers/resolve/mounts/license
  /opt/resolve/'Resolve Disk Database'  -> /home/pil/containers/resolve/mounts/database
  /var/BlackmagicDesign/DaVinci Resolve -> /home/pil/containers/resolve/mounts/BlackmagicDesign
  /opt/resolve/Media                    -> /home/pil/containers/resolve/mounts/Media
ActCCMessage Already in Table: Code= c005, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= c006, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= c007, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= 2282, Mode=  0, Level=  0, CmdKey= 8, Option= 0
PnlMsgActionStringAdapter Already in Table: Code= 615e, Mode=  0, Level=  0, CmdKey= -1, Option= 0
log4cxx: No appender could be found for logger (BtCommon).
log4cxx: Please initialize the log4cxx system properly.

./resolve.sh /bin/bash give me the prompt

I have ubuntu 22.04.

any idea ?

regards,

**Comment by cowmix** [comment]
If you just run:

./resolve.sh  

(without the /bin/bash) what happens?

**Comment by pperquin** [comment]
Hi Cowmix,

It reply this :

/home/pil/containers/resolve
PODMAN
/home/pil/containers/resolve
non-network local connections being added to access control list
The container's /etc/machine-id : f9e164346eb00127f7c72b8e4b951048
The network driver setting is : --network=none
Bind-mounted directories of interest :
CONTAINER (CentOS 8) -> HOST (Ubuntu)
/home/resolve -> /home/pil/containers/resolve/mounts/resolve-home
/opt/resolve/logs -> /home/pil/containers/resolve/mounts/logs
/opt/resolve/configs -> /home/pil/containers/resolve/mounts/configs
/opt/resolve/easyDCP -> /home/pil/containers/resolve/mounts/easyDCP
/opt/resolve/.license -> /home/pil/containers/resolve/mounts/license
/opt/resolve/'Resolve Disk Database' -> /home/pil/containers/resolve/mounts/database
/var/BlackmagicDesign/DaVinci Resolve -> /home/pil/containers/resolve/mounts/BlackmagicDesign
/opt/resolve/Media -> /home/pil/containers/resolve/mounts/Media
ActCCMessage Already in Table: Code= c005, Mode= 13, Level= 1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= c006, Mode= 13, Level= 1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= c007, Mode= 13, Level= 1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= 2282, Mode= 0, Level= 0, CmdKey= 8, Option= 0
PnlMsgActionStringAdapter Already in Table: Code= 615e, Mode= 0, Level= 0, CmdKey= -1, Option= 0
log4cxx: No appender could be found for logger (BtCommon).
log4cxx: Please initialize the log4cxx system properly.

I make this try with the 18.0b2, I also try with 17.4.6 but it was the same problem. I search in forums and it seem a know problem without a clear solution.

May be i will try to make the same type of script butt with pop_os.

regards,

**Comment by fat-tire** [comment]
Hope you were able to fix this :)
